version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/html